version: '3.5'

services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
    command: redis-server --save 60 1 --loglevel warning
